### ISSUE TITLE
Armory High Memory Usage

### ISSUE THREAD

**Issue by dariusc93** [etotheipi/BitcoinArmory#132]
I notice that armory is consuming more than 50% of my ram while running which is nearly 4GB to 5GB out of 8GB. This did slow other programs down and did cause armory to silently crashed due to OOM. I do not know if this is a bug, but I thought I report it since I didnt find to much information about it. bitcoind doesnt use to much memory.

Version I am currently using 0.88.1

**Comment by rippler** [comment]
Has this been fixed in a later release?

**Comment by dariusc93** [comment]
I believe it have been fixed

**Comment by rippler** [comment]
I noticed high resource usage in v0.92.*, although "Reduced RAM" appears in a release note for an earlier version.
I just updated to the current version and will submit my findings if I spot the problem again.

**Comment by STRML** [comment]
We are seeing far higher RAM usage in the new 0.93 beta than in previous versions, 2x or more. We are investigating but it is high priority for us as the machines we have specced to run Armory are no longer capable of running it properly with the new memory requirements.

**Comment by seepib** [comment]
Dual Xeon E5620 with 24GB of RAM, Is what i have - new memory requirements??? what are they..   Using 22GB-23GB of my stack. :(  <-- that's a a sad face if you missed it.

oo. running v0.93.3

Very :( faces

**Comment by achow101** [comment]
@seepib Armory is no longer maintained in this repository. It has been moved to https://github.com/goatpig/BitcoinArmory/

You are using an outdated version. Update to Armory 0.95.1
